#!/bin/bash

echo "=> Building EasyLogin Server"

docker run --rm -v $(pwd):/EasyLoginServer -v /var/run/docker.sock:/var/run/docker.sock ibmcom/swift-ubuntu:latest bash -c "cd /EasyLogin && swift package clean && swift build --configuration release"

exit $?
